name: Update README with random image

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate random image
      id: random-image
      run: |
        IMAGES=("knight_flower.gif" "megatron.gif")
        IMAGE_INDEX=$(($(date +'%j') % ${#IMAGES[@]}))
        echo "IMAGE=${IMAGES[$IMAGE_INDEX]}" >> $GITHUB_ENV

    - name: Update README
      run: |
        sed -i "s|<img data-showcase src=\"[^\"]*\"|<img data-showcase src=\"$IMAGE\"|" README.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git diff --quiet && exit 0
        git commit -am "Update README showcase"
        git push
